name: Daily Random Commits

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC (10:30 AM IST)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "Rahul Joshi"
          git config --global user.email "rj1342627@gmail.com"

      - name: Make multiple random commits
        run: |
          echo "Starting random commits..."
          COUNT=$(( ( RANDOM % 10 ) + 3 ))  # Random number between 3 and 12
          echo "Will make $COUNT commits today."

          for i in $(seq 1 $COUNT)
          do
            echo "Commit #$i on $(date)" >> activity_log.txt
            git add activity_log.txt
            git commit -m "Random commit #$i on $(date)"
            sleep 1  # Optional: short delay to make commits look natural
          done

      - name: Push changes
        run: |
          echo "Setting remote with token"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
