name: Daily Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC (10:30 AM IST)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "Rahul Joshi"
          git config --global user.email "rj1342627@gmail.com"

      - name: Debug Git Status
        run: |
          echo "Checking current repo status"
          git status
          git remote -v

      - name: Make a commit
        run: |
          echo "Updated on $(date)" >> activity_log.txt
          git add activity_log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"

      - name: Push changes
        run: |
          echo "Setting remote with token"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
